import pandas as pd
import plotly.graph_objects as go

from heatpro.check import ENERGY_FEATURE_NAME, WEIGHT_NAME_REQUIRED

def plot_weekly_industry_profile(weekly_industry_non_normalized: pd.DataFrame) -> go.Figure:
    fig =  go.Figure(
                go.Scatter(
                    x = weekly_industry_non_normalized.index,
                    y = weekly_industry_non_normalized[WEIGHT_NAME_REQUIRED],
                    name = "Residential heat demand including hot water",
                ),
                layout_yaxis_title = "<b></b>",
                layout_title_text = "Hot water sociological consumption profile"
            )
    fig.add_vline(x=24, line_color="rgba(0, 0, 0, 0.5)")\
        .add_vline(x=24*2, line_color="rgba(0, 0, 0, 0.5)")\
        .add_vline(x=24*3, line_color="rgba(0, 0, 0, 0.5)")\
        .add_vline(x=24*4, line_color="rgba(0, 0, 0, 0.5)")\
        .add_vline(x=24*5, line_color="rgba(0, 0, 0, 0.5)")\
        .add_vline(x=24*6, line_color="rgba(0, 0, 0, 0.5)")
    return fig

def generate_default_yearly_industry_demand(year_index: pd.DatetimeIndex) -> pd.DataFrame:
    return pd.DataFrame(
                                                            [55_700_000] * len(year_index),
                                                            columns=[ENERGY_FEATURE_NAME],
                                                            index=year_index,
                                                        )
    
def generate_weekly_industry_profile() -> pd.DataFrame:
    return pd.DataFrame(
                                    [ 
                                        ['monday',0,1.0],
                                        ['monday',1,1.0],
                                        ['monday',2,1.0],
                                        ['monday',3,1.0],
                                        ['monday',4,1.0],
                                        ['monday',5,1.0],
                                        ['monday',6,1.0],
                                        ['monday',7,1.0],
                                        ['monday',8,1.0],
                                        ['monday',9,1.0],
                                        ['monday',10,1.0],
                                        ['monday',11,1.0],
                                        ['monday',12,1.0],
                                        ['monday',13,1.0],
                                        ['monday',14,1.0],
                                        ['monday',15,1.0],
                                        ['monday',16,1.0],
                                        ['monday',17,1.0],
                                        ['monday',18,1.0],
                                        ['monday',19,1.0],
                                        ['monday',20,1.0],
                                        ['monday',21,1.0],
                                        ['monday',22,1.0],
                                        ['monday',23,1.0],
                                        ['tuesday',0,1.0],
                                        ['tuesday',1,1.0],
                                        ['tuesday',2,1.0],
                                        ['tuesday',3,1.0],
                                        ['tuesday',4,1.0],
                                        ['tuesday',5,1.0],
                                        ['tuesday',6,1.0],
                                        ['tuesday',7,1.0],
                                        ['tuesday',8,1.0],
                                        ['tuesday',9,1.0],
                                        ['tuesday',10,1.0],
                                        ['tuesday',11,1.0],
                                        ['tuesday',12,1.0],
                                        ['tuesday',13,1.0],
                                        ['tuesday',14,1.0],
                                        ['tuesday',15,1.0],
                                        ['tuesday',16,1.0],
                                        ['tuesday',17,1.0],
                                        ['tuesday',18,1.0],
                                        ['tuesday',19,1.0],
                                        ['tuesday',20,1.0],
                                        ['tuesday',21,1.0],
                                        ['tuesday',22,1.0],
                                        ['tuesday',23,1.0],
                                        ['wednesday',0,1.0],
                                        ['wednesday',1,1.0],
                                        ['wednesday',2,1.0],
                                        ['wednesday',3,1.0],
                                        ['wednesday',4,1.0],
                                        ['wednesday',5,1.0],
                                        ['wednesday',6,1.0],
                                        ['wednesday',7,1.0],
                                        ['wednesday',8,1.0],
                                        ['wednesday',9,1.0],
                                        ['wednesday',10,1.0],
                                        ['wednesday',11,1.0],
                                        ['wednesday',12,1.0],
                                        ['wednesday',13,1.0],
                                        ['wednesday',14,1.0],
                                        ['wednesday',15,1.0],
                                        ['wednesday',16,1.0],
                                        ['wednesday',17,1.0],
                                        ['wednesday',18,1.0],
                                        ['wednesday',19,1.0],
                                        ['wednesday',20,1.0],
                                        ['wednesday',21,1.0],
                                        ['wednesday',22,1.0],
                                        ['wednesday',23,1.0],
                                        ['thursday',0,1.0],
                                        ['thursday',1,1.0],
                                        ['thursday',2,1.0],
                                        ['thursday',3,1.0],
                                        ['thursday',4,1.0],
                                        ['thursday',5,1.0],
                                        ['thursday',6,1.0],
                                        ['thursday',7,1.0],
                                        ['thursday',8,1.0],
                                        ['thursday',9,1.0],
                                        ['thursday',10,1.0],
                                        ['thursday',11,1.0],
                                        ['thursday',12,1.0],
                                        ['thursday',13,1.0],
                                        ['thursday',14,1.0],
                                        ['thursday',15,1.0],
                                        ['thursday',16,1.0],
                                        ['thursday',17,1.0],
                                        ['thursday',18,1.0],
                                        ['thursday',19,1.0],
                                        ['thursday',20,1.0],
                                        ['thursday',21,1.0],
                                        ['thursday',22,1.0],
                                        ['thursday',23,1.0],
                                        ['friday',0,1.0],
                                        ['friday',1,1.0],
                                        ['friday',2,1.0],
                                        ['friday',3,1.0],
                                        ['friday',4,1.0],
                                        ['friday',5,1.0],
                                        ['friday',6,1.0],
                                        ['friday',7,1.0],
                                        ['friday',8,1.0],
                                        ['friday',9,1.0],
                                        ['friday',10,1.0],
                                        ['friday',11,1.0],
                                        ['friday',12,1.0],
                                        ['friday',13,1.0],
                                        ['friday',14,1.0],
                                        ['friday',15,1.0],
                                        ['friday',16,1.0],
                                        ['friday',17,1.0],
                                        ['friday',18,1.0],
                                        ['friday',19,1.0],
                                        ['friday',20,1.0],
                                        ['friday',21,1.0],
                                        ['friday',22,1.0],
                                        ['friday',23,1.0],
                                        ['saturday',0,1.0],
                                        ['saturday',1,1.0],
                                        ['saturday',2,1.0],
                                        ['saturday',3,1.0],
                                        ['saturday',4,1.0],
                                        ['saturday',5,1.0],
                                        ['saturday',6,1.0],
                                        ['saturday',7,1.0],
                                        ['saturday',8,1.0],
                                        ['saturday',9,1.0],
                                        ['saturday',10,1.0],
                                        ['saturday',11,1.0],
                                        ['saturday',12,1.0],
                                        ['saturday',13,1.0],
                                        ['saturday',14,1.0],
                                        ['saturday',15,1.0],
                                        ['saturday',16,1.0],
                                        ['saturday',17,1.0],
                                        ['saturday',18,1.0],
                                        ['saturday',19,1.0],
                                        ['saturday',20,1.0],
                                        ['saturday',21,1.0],
                                        ['saturday',22,1.0],
                                        ['saturday',23,1.0],
                                        ['sunday',0,1.0],
                                        ['sunday',1,1.0],
                                        ['sunday',2,1.0],
                                        ['sunday',3,1.0],
                                        ['sunday',4,1.0],
                                        ['sunday',5,1.0],
                                        ['sunday',6,1.0],
                                        ['sunday',7,1.0],
                                        ['sunday',8,1.0],
                                        ['sunday',9,1.0],
                                        ['sunday',10,1.0],
                                        ['sunday',11,1.0],
                                        ['sunday',12,1.0],
                                        ['sunday',13,1.0],
                                        ['sunday',14,1.0],
                                        ['sunday',15,1.0],
                                        ['sunday',16,1.0],
                                        ['sunday',17,1.0],
                                        ['sunday',18,1.0],
                                        ['sunday',19,1.0],
                                        ['sunday',20,1.0],
                                        ['sunday',21,1.0],
                                        ['sunday',22,1.0],
                                        ['sunday',23,1.0],
                                        ],
                                    columns=['day','hour',WEIGHT_NAME_REQUIRED]
                                )