import numpy as np
import pandas as pd
import plotly.graph_objects as go

from heatpro.check import ENERGY_FEATURE_NAME, WEIGHT_NAME_REQUIRED

def plot_monthly_building_load(monthly_building_load_df: pd.DataFrame) -> go.Figure:
    return go.Figure(
                go.Scatter(
                    x = monthly_building_load_df.index,
                    y = monthly_building_load_df[ENERGY_FEATURE_NAME],
                    name = "Residential heat demand including hot water",
                ),
                layout_yaxis_title = "<b>kWh</b>",
                layout_title_text = "Residential heat demand including hot water"
            )
    
def plot_weekly_residential_profile(weekly_non_normalized_residential_profile: pd.DataFrame) -> go.Figure:
    fig =  go.Figure(
                go.Scatter(
                    x = weekly_non_normalized_residential_profile.index,
                    y = weekly_non_normalized_residential_profile[WEIGHT_NAME_REQUIRED],
                    name = "Residential heat demand profile",
                ),
                layout_yaxis_title = "<b></b>",
                layout_title_text = "Residential heat demand weekly profile"
            )
    fig.add_vline(x=24, line_color="rgba(0, 0, 0, 0.5)")\
        .add_vline(x=24*2, line_color="rgba(0, 0, 0, 0.5)")\
        .add_vline(x=24*3, line_color="rgba(0, 0, 0, 0.5)")\
        .add_vline(x=24*4, line_color="rgba(0, 0, 0, 0.5)")\
        .add_vline(x=24*5, line_color="rgba(0, 0, 0, 0.5)")\
        .add_vline(x=24*6, line_color="rgba(0, 0, 0, 0.5)")
    return fig
    
def generate_default_monthly_building_load(month_index: pd.DatetimeIndex) -> pd.DataFrame:
    return pd.DataFrame(
                                    50000 * np.concatenate(
                                                list(np.array([
                                                            2068,
                                                            1696,
                                                            1268,
                                                            727,
                                                            609,
                                                            194,
                                                            164,
                                                            177,
                                                            208,
                                                            1013,
                                                            1139,
                                                            1894,]) 
                                                     for k in range(len(month_index)//12))
                                                )[:len(month_index)],
                                    index = month_index,
                                    columns=[ENERGY_FEATURE_NAME]
                                )
    
def generate_default_residential_profile() -> pd.DataFrame:
    return pd.DataFrame(
                                    [ 
                                        ['monday',0,0.9963],
                                        ['monday',1,0.8767],
                                        ['monday',2,0.9166],
                                        ['monday',3,0.9863],
                                        ['monday',4,1.0660],
                                        ['monday',5,1.1258],
                                        ['monday',6,1.1656],
                                        ['monday',7,1.1955],
                                        ['monday',8,1.1955],
                                        ['monday',9,1.1955],
                                        ['monday',10,1.1756],
                                        ['monday',11,1.1557],
                                        ['monday',12,1.1357],
                                        ['monday',13,1.1158],
                                        ['monday',14,1.0859],
                                        ['monday',15,1.0660],
                                        ['monday',16,1.0361],
                                        ['monday',17,0.9963],
                                        ['monday',18,0.9365],
                                        ['monday',19,0.8667],
                                        ['monday',20,0.7870],
                                        ['monday',21,0.6974],
                                        ['monday',22,0.6177],
                                        ['monday',23,0.6077],
                                        ['tuesday',0,0.9963],
                                        ['tuesday',1,0.8767],
                                        ['tuesday',2,0.9166],
                                        ['tuesday',3,0.9863],
                                        ['tuesday',4,1.0660],
                                        ['tuesday',5,1.1258],
                                        ['tuesday',6,1.1656],
                                        ['tuesday',7,1.1955],
                                        ['tuesday',8,1.1955],
                                        ['tuesday',9,1.1955],
                                        ['tuesday',10,1.1756],
                                        ['tuesday',11,1.1557],
                                        ['tuesday',12,1.1357],
                                        ['tuesday',13,1.1158],
                                        ['tuesday',14,1.0859],
                                        ['tuesday',15,1.0660],
                                        ['tuesday',16,1.0361],
                                        ['tuesday',17,0.9963],
                                        ['tuesday',18,0.9365],
                                        ['tuesday',19,0.8667],
                                        ['tuesday',20,0.7870],
                                        ['tuesday',21,0.6974],
                                        ['tuesday',22,0.6177],
                                        ['tuesday',23,0.6077],
                                        ['wednesday',0,0.9963],
                                        ['wednesday',1,0.8767],
                                        ['wednesday',2,0.9166],
                                        ['wednesday',3,0.9863],
                                        ['wednesday',4,1.0660],
                                        ['wednesday',5,1.1258],
                                        ['wednesday',6,1.1656],
                                        ['wednesday',7,1.1955],
                                        ['wednesday',8,1.1955],
                                        ['wednesday',9,1.1955],
                                        ['wednesday',10,1.1756],
                                        ['wednesday',11,1.1557],
                                        ['wednesday',12,1.1357],
                                        ['wednesday',13,1.1158],
                                        ['wednesday',14,1.0859],
                                        ['wednesday',15,1.0660],
                                        ['wednesday',16,1.0361],
                                        ['wednesday',17,0.9963],
                                        ['wednesday',18,0.9365],
                                        ['wednesday',19,0.8667],
                                        ['wednesday',20,0.7870],
                                        ['wednesday',21,0.6974],
                                        ['wednesday',22,0.6177],
                                        ['wednesday',23,0.6077],
                                        ['thursday',0,0.6077],
                                        ['thursday',1,0.9963],
                                        ['thursday',2,0.8767],
                                        ['thursday',3,0.9166],
                                        ['thursday',4,0.9863],
                                        ['thursday',5,1.0660],
                                        ['thursday',6,1.1258],
                                        ['thursday',7,1.1656],
                                        ['thursday',8,1.1955],
                                        ['thursday',9,1.1955],
                                        ['thursday',10,1.1955],
                                        ['thursday',11,1.1756],
                                        ['thursday',12,1.1557],
                                        ['thursday',13,1.1357],
                                        ['thursday',14,1.1158],
                                        ['thursday',15,1.0859],
                                        ['thursday',16,1.0660],
                                        ['thursday',17,1.0361],
                                        ['thursday',18,0.9963],
                                        ['thursday',19,0.9365],
                                        ['thursday',20,0.8667],
                                        ['thursday',21,0.7870],
                                        ['thursday',22,0.6974],
                                        ['thursday',23,0.6177],
                                        ['friday',0,0.6077],
                                        ['friday',1,0.9963],
                                        ['friday',2,0.8767],
                                        ['friday',3,0.9166],
                                        ['friday',4,0.9863],
                                        ['friday',5,1.0660],
                                        ['friday',6,1.1258],
                                        ['friday',7,1.1656],
                                        ['friday',8,1.1955],
                                        ['friday',9,1.1955],
                                        ['friday',10,1.1955],
                                        ['friday',11,1.1756],
                                        ['friday',12,1.1557],
                                        ['friday',13,1.1357],
                                        ['friday',14,1.1158],
                                        ['friday',15,1.0859],
                                        ['friday',16,1.0660],
                                        ['friday',17,1.0361],
                                        ['friday',18,0.9963],
                                        ['friday',19,0.9365],
                                        ['friday',20,0.8667],
                                        ['friday',21,0.7870],
                                        ['friday',22,0.6974],
                                        ['friday',23,0.6177],
                                        ['saturday',0,0.6077],
                                        ['saturday',1,0.9963],
                                        ['saturday',2,0.8767],
                                        ['saturday',3,0.9166],
                                        ['saturday',4,0.9863],
                                        ['saturday',5,1.0660],
                                        ['saturday',6,1.1258],
                                        ['saturday',7,1.1656],
                                        ['saturday',8,1.1955],
                                        ['saturday',9,1.1955],
                                        ['saturday',10,1.1955],
                                        ['saturday',11,1.1756],
                                        ['saturday',12,1.1557],
                                        ['saturday',13,1.1357],
                                        ['saturday',14,1.1158],
                                        ['saturday',15,1.0859],
                                        ['saturday',16,1.0660],
                                        ['saturday',17,1.0361],
                                        ['saturday',18,0.9963],
                                        ['saturday',19,0.9365],
                                        ['saturday',20,0.8667],
                                        ['saturday',21,0.7870],
                                        ['saturday',22,0.6974],
                                        ['saturday',23,0.6177],
                                        ['sunday',0,0.6077],
                                        ['sunday',1,0.9963],
                                        ['sunday',2,0.8767],
                                        ['sunday',3,0.9166],
                                        ['sunday',4,0.9863],
                                        ['sunday',5,1.0660],
                                        ['sunday',6,1.1258],
                                        ['sunday',7,1.1656],
                                        ['sunday',8,1.1955],
                                        ['sunday',9,1.1955],
                                        ['sunday',10,1.1756],
                                        ['sunday',11,1.1557],
                                        ['sunday',12,1.1357],
                                        ['sunday',13,1.1158],
                                        ['sunday',14,1.0859],
                                        ['sunday',15,1.0660],
                                        ['sunday',16,1.0361],
                                        ['sunday',17,0.9963],
                                        ['sunday',18,0.9365],
                                        ['sunday',19,0.8667],
                                        ['sunday',20,0.7870],
                                        ['sunday',21,0.6974],
                                        ['sunday',22,0.6177],
                                        ['sunday',23,0.6077],
                                        ],
                                    columns=['day','hour',WEIGHT_NAME_REQUIRED]
                                )